---
# password.yml
- win_domain_user:
    domain_server: "{{ ansible_domain }}"
    domain_username: "{{ ansible_user }}"
    domain_password: "{{ ansible_password }}"
    name: "{{ item.name }}"
    password: "{{ item.value }}"
    state: present
    groups: Domain Users