---
- name: Create directory for vulnerable service
  win_file:
    path: "C:\\Software\\Snow Software\\Inventory\\Agent"
    state: directory

- name: Create vulnerable service by copying legitimate service bunary
  win_copy:
    remote_src: yes
    src: "C:\\Windows\\System32\\snmptrap.exe"
    dest: "C:\\Software\\Snow Software\\Inventory\\Agent\\snowagent.exe"

- name: Update folder ACLs
  win_acl:
    user: BUILTIN\Users
    path: "C:\\Software\\Snow Software\\"
    rights: FullControl, Modify
    type: allow
    state: absent

- name: Update folder ACLs
  win_acl:
    user: Users
    path: "C:\\Software\\Snow Software\\"
    rights: FullControl, Modify
    type: allow
    state: absent

- name: Create vulnerable service
  win_service:
    name: snwsoft
    description: Snow Software Ltd
    start_mode: manual
    username: LocalSystem
    path: "C:\\Software\\Snow Software\\Inventory\\Agent\\snowagent.exe"

- win_command: sc sdset snwsoft D:(A;;CCLCSWRPWPDTLOCRRC;;;SY)(A;;CCDCLCSWRPWPDTLOCRSDRCWDWO;;;BA)(A;;CCLCSWLOCRRC;;;IU)(A;;CCLCSWLOCRRC;;;SU)(A;;CCLCSWRCRPWP;;;AU)S:(AU;FA;CCDCLCSWRPWPDTLOCRSDRCWDWO;;;WD)