---
# create.yml
- win_domain_user:
    domain_server: "{{ ansible_domain }}"
    domain_username: "{{ ansible_user }}"
    domain_password: "{{ ansible_password }}"
    name: "{{ item.name }}"
    password: "{{ lookup('password', 'credentials/user/' + item.name + ' chars=ascii_letters,digits,punctuation length=12') }}"
    state: present
    groups: Domain Users