- hosts: add_insecure_share
  user: '{{ ansible_user }}'
  tasks:       
    #create network share
    - name: Share Folder
      win_share:
        name: Network-Administration
        description: top secret share
        path: C:\Network-Administration
        list: yes
        full: Administrators
        read: Users