---
# file: site.yml
- hosts: AD*
  tasks:
    - set_fact:
        attributes_dict: "{{ attributes_dict | default({}) | combine({item.name: item.value}) }}"
      with_items:
        - "{{ attributes }}"
  any_errors_fatal: true
#- import_playbook: plays/networks.yml
- import_playbook: plays/domains.yml
  any_errors_fatal: true
- import_playbook: plays/systems.yml
  any_errors_fatal: true
- import_playbook: plays/attacks.yml
  any_errors_fatal: true

# Clean up
- import_playbook: plays/cleanup.yml
  any_errors_fatal: true

#- import_playbook: plays/custom.yml