---
# user_create.yml
- win_group_membership:
    name: Remote Desktop Users
    members:
      - alfa\Samuel.Briggs
    state: present
    domain_server: R0-T0-DC-001.alfa.lab
    domain_username: alfa\administrator
    domain_password: tX8Hf7kKXKKmI
