- set_fact:
    AD_Create: "{{ AD_Create | default({}) | combine({item.name: item.value}) }}"
  with_items:
    - "{{ attributes_dict.AD_Create }}"
- name: Installing AD Domain Services & Creating new Windows forest
  win_feature:
    name: AD-Domain-Services
    include_management_tools: yes
    include_sub_features: yes
- name: Changing system hostname.
  win_hostname:
    name: "{{ custom_hostname }}"
  when: ansible_os_family == "Windows"
- win_domain:
    database_path: C:\Windows\NTDS
    dns_domain_name: "{{ AD_Create.domain_netbios_name + '.lab' }}"
    domain_netbios_name: "{{ AD_Create.domain_netbios_name }}"
    safe_mode_password: TnUBqUJP62vpBqps4aXWwKZndg4DAg8GvKwYUD6TWg
    sysvol_path: C:\Windows\SYSVOL
  register: domain
- name: Restarting and testing domain availability (Estimated 5-10 mins).
  win_reboot:
    connect_timeout: 15
    post_reboot_delay: 60
    test_command: 'exit (Get-Service -Name Netlogon).Status -ne "Running"'
  when: domain.reboot_required
- win_command: "nltest /dsgetdc:"
  register: command_result
  until: command_result.rc == 0
  retries: 90
  delay: 10
- win_shell: "if ((Get-KdsRootKey).Length -Eq 0) { Add-KdsRootKey –EffectiveTime ((get-date).addhours(-10)) }"
- win_feature:
    name: Windows-Defender
    state: absent