- set_fact:
    AD_Join: "{{ AD_Join | default({}) | combine({item.name: item.value}) }}"
  with_items:
    - "{{ attributes_dict.AD_Join }}"
- name: Set look-up address
  win_dns_client:
    adapter_names: '*'
    ipv4_addresses:
    - "{{ AD_Join.domain_dns_server }}"
    log_path: C:\dns_log.txt
- win_feature:
    name: RSAT-AD-PowerShell
- win_feature:
    name: Windows-Defender
    state: absent
- name: Joining system(s) to domain.
  win_domain_membership:
    dns_domain_name: "{{ AD_Join.domain_netbios_name + '.lab' }}"
    domain_admin_user: "{{ 'administrator@' + AD_Join.domain_netbios_name + '.lab' }}"
    hostname: "{{ custom_hostname }}"
    domain_admin_password: "{{ ansible_password }}"
    state: domain
  register: domain_state
  retries: 10
  delay: 60
- win_reboot:
  when: domain_state.reboot_required
- set_fact:
    ansible_winrm_transport: ntlm
    ansible_domain: "{{ AD_Join.domain_netbios_name + '.lab' }}"
    ansible_user: "{{ 'administrator@' + AD_Join.domain_netbios_name + '.lab'}}"
    ansible_password: "{{ ansible_password }}"