---
- include_vars:
    file: env.yml
- debug:
    var: AD_Users[0]
- include_tasks: tasks/AD/user_create.yml
  vars:
    user: "{{ AD_Users[0] }}"
- include_tasks: tasks/windows/rdp/allow.yml
  vars:
    user: "{{ AD_Users[0] }}"
  register: user
